apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aks-store-ing
spec:
  ingressClassName: internal
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: store-front
            port:
              number: 80